# Connect to SQL

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "database username"
password = quote_plus("your password")
host = "your name host"
port = "your port"
database = "your database"

DATABASE_URL = (
    f"postgresql://{username}:{password}@{host}:{port}/{database}"
)

engine = create_engine(DATABASE_URL)

# Data Preprocessing

### **IMPORT**

In [ ]:
import pandas as pd
import numpy as np

### **Read Dataset**

In [ ]:
telco = pd.read_excel('https://raw.githubusercontent.com/rezanagita/telecommunication-analytics/main/dataset%20telco.xlsx')
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,Area,Cluster,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Month,Churn_Flag,NPS_Score,Target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Jogja,Bandng,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010
1,TEL-000002,SUB1687,10/07/2024,SBY,Yogyakarta,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332
2,TEL-000003,SUB3131,13/03/2024,Yogyakarta,Jakrta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577
3,TEL-000004,SUB4293,11/02/2026,Bandng,Jakrta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707
4,TEL-000005,SUB4930,Jan-16-2026,SBY,Jakarta,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593

In [ ]:
telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Txn_ID           10000 non-null  object
 1   Subscriber_ID    9432 non-null   object
 2   Activation_Date  10000 non-null  object
 3   Area             10000 non-null  object
 4   Cluster          10000 non-null  object
 5   Package_Type     10000 non-null  object
 6   Package_Name     10000 non-null  object
 7   Usage_GB         10000 non-null  int64
 8   Package_Price    10000 non-null  float64
 9   Discount_Pct     9190 non-null   float64
 10  Recharge_Amount  10000 non-null  float64
 11  Network_Cost     10000 non-null  float64
 12  Channel          10000 non-null  object
 13  Payment_Method   10000 non-null  object
 14  Tenure_Month     10000 non-null  int64
 15  Churn_Flag       6673 non-null   object
 16  NPS_Score        10000 non-null  int64
 17  Target_ARPU      10000 non-null  int64
dtypes: float64(4), int64(4), object(10)
memory usage: 1.4+ MB

In [ ]:
telco.describe()

,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Tenure_Month,NPS_Score,Target_ARPU
count,10000.000000,10000.000000,9190.000000,1.000000e+04,1.000000e+04,10000.00000,10000.000000,10000.00000
mean,44.835700,1789.569845,0.339129,5.092496e+04,3.890045e+04,57.07490,50.482300,109651.59560
std,339.335103,11039.918381,0.332683,1.741108e+06,1.000913e+06,36.11306,40.611516,51963.35388
min,1.000000,10.130000,0.000000,1.280000e+00,1.080000e+00,-5.00000,-20.000000,20069.00000
25%,5.000000,258.930000,0.062500,6.673375e+02,5.747000e+02,26.00000,15.000000,64878.75000
50%,11.000000,513.785000,0.150000,2.384555e+03,2.055935e+03,57.00000,51.000000,109237.50000
75%,16.000000,763.702500,0.750000,5.939977e+03,5.277805e+03,88.00000,85.000000,155002.25000
max,4935.000000,149023.620000,0.950000,1.642417e+08,8.613749e+07,120.00000,120.000000,199987.00000

### **Rename column**

In [ ]:
# Rename column Area = City, Cluster = Province
telco.rename(columns={'Area': 'City', 'Cluster': 'Province'}, inplace=True)
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Month,Churn_Flag,NPS_Score,Target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Jogja,Bandng,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010
1,TEL-000002,SUB1687,10/07/2024,SBY,Yogyakarta,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332
2,TEL-000003,SUB3131,13/03/2024,Yogyakarta,Jakrta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577
3,TEL-000004,SUB4293,11/02/2026,Bandng,Jakrta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707
4,TEL-000005,SUB4930,Jan-16-2026,SBY,Jakarta,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593

In [ ]:
telco.rename(columns={'Tenure_Month': 'Tenure_Days'}, inplace=True)

### **Ubah value type data: Activation_Date**

In [ ]:
# Mengubah Tipe data ke datetime
telco['Activation_Date'] = pd.to_datetime(telco['Activation_Date'], format='mixed', dayfirst=True)
telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Txn_ID           10000 non-null  object
 1   Subscriber_ID    9432 non-null   object
 2   Activation_Date  10000 non-null  datetime64[ns]
 3   City             10000 non-null  object
 4   Province         10000 non-null  object
 5   Package_Type     10000 non-null  object
 6   Package_Name     10000 non-null  object
 7   Usage_GB         10000 non-null  int64
 8   Package_Price    10000 non-null  float64
 9   Discount_Pct     9190 non-null   float64
 10  Recharge_Amount  10000 non-null  float64
 11  Network_Cost     10000 non-null  float64
 12  Channel          10000 non-null  object
 13  Payment_Method   10000 non-null  object
 14  Tenure_Days      10000 non-null  int64
 15  Churn_Flag       6673 non-null   object
 16  NPS_Score        10000 non-null  int64
 17  Target_ARPU      10000 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(4), object(9)
memory usage: 1.4+ MB

### **Merapikan value activation date**
ganti 2026 menjadi 2025

In [ ]:
latest_date= telco['Activation_Date'].max()
latest_date

Timestamp('2026-06-19 00:00:00')

In [ ]:
# mengganti tahun 2026 menjadi 2025
# Karena 'Activation_Date' adalah tipe datetime, kita gunakan
telco['Activation_Date'] = telco['Activation_Date'].apply(lambda x: x.replace(year=2025) if x.year == 2026 else x)
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Jogja,Bandng,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010
1,TEL-000002,SUB1687,2024-07-10,SBY,Yogyakarta,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332
2,TEL-000003,SUB3131,2024-03-13,Yogyakarta,Jakrta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577
3,TEL-000004,SUB4293,2025-02-11,Bandng,Jakrta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707
4,TEL-000005,SUB4930,2025-01-16,SBY,Jakarta,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593

In [ ]:
latest_date= telco['Activation_Date'].max()
latest_date

Timestamp('2025-12-31 00:00:00')

### **Merapikan nama City dan Province**

In [ ]:
# Melihat value unik di city
telco['City'].unique()

array(['Jogja', 'SBY', 'Yogyakarta', 'Bandng', 'Jakarta', 'JAKARTA',
       'Jakrta', 'Surabaya', 'JKT', 'Bandung'], dtype=object)

In [ ]:
# Merapikan value City
city_mapping = {
    'Jogja': 'Yogyakarta',
    'SBY': 'Surabaya',
    'Bandng': 'Bandung',
    'JAKARTA': 'Jakarta',
    'Jakrta': 'Jakarta',
    'JKT': 'Jakarta'
}
telco['City'] = telco['City'].replace(city_mapping)
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,Bandng,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010
1,TEL-000002,SUB1687,2024-07-10,Surabaya,Yogyakarta,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332
2,TEL-000003,SUB3131,2024-03-13,Yogyakarta,Jakrta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577
3,TEL-000004,SUB4293,2025-02-11,Bandung,Jakrta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707
4,TEL-000005,SUB4930,2025-01-16,Surabaya,Jakarta,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593

In [ ]:
# Melihat value unik di Province
telco['Province'].unique()

array(['Bandng', 'Yogyakarta', 'Jakrta', 'Jakarta', 'Jogja', 'Sby',
       'Surabaya', 'Bandung'], dtype=object)

In [ ]:
telco['Province'] = telco['City'].map(
    {
        'Yogyakarta': 'DIY',
        'Surabaya': 'Jawa Timur',
        'Bandung': 'Jawa Barat',
        'Jakarta': 'DKI'
    }
)
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,DIY,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010
1,TEL-000002,SUB1687,2024-07-10,Surabaya,Jawa Timur,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332
2,TEL-000003,SUB3131,2024-03-13,Yogyakarta,DIY,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577
3,TEL-000004,SUB4293,2025-02-11,Bandung,Jawa Barat,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707
4,TEL-000005,SUB4930,2025-01-16,Surabaya,Jawa Timur,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593

### **Merapikan value Channel**

In [ ]:
# Melihat value unik di Channel
telco['Channel'].unique()

array(['Retail', 'Dealer', 'dealer', 'Online'], dtype=object)

In [ ]:
# ubah dealer ke Dealer
telco['Channel'] = telco['Channel'].replace('dealer', 'Dealer')

In [ ]:
# Melihat value unik di Channel
telco['Channel'].unique()

array(['Retail', 'Dealer', 'Online'], dtype=object)

### **Handling tenure_month**

In [ ]:
# menghilangkan tanda minus
telco['Tenure_Days'] = telco['Tenure_Days'].abs()
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,DIY,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010
1,TEL-000002,SUB1687,2024-07-10,Surabaya,Jawa Timur,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332
2,TEL-000003,SUB3131,2024-03-13,Yogyakarta,DIY,Data,Package_61,14,194.08,0.10,1976.69,2069.26,Dealer,Transfer,81,N,96,154577
3,TEL-000004,SUB4293,2025-02-11,Bandung,Jawa Barat,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707
4,TEL-000005,SUB4930,2025-01-16,Surabaya,Jawa Timur,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593

### **Handle Missing Value**

In [ ]:
telco.isnull().sum()

Txn_ID                0
Subscriber_ID       568
Activation_Date       0
City                  0
Province              0
Package_Type          0
Package_Name          0
Usage_GB              0
Package_Price         0
Discount_Pct        810
Recharge_Amount       0
Network_Cost          0
Channel               0
Payment_Method        0
Tenure_Days           0
Churn_Flag         3327
NPS_Score             0
Target_ARPU           0
dtype: int64

In [ ]:
telco['Discount_Pct'].isna().sum()

np.int64(810)

In [ ]:
telco['Discount_Pct'].isna().mean() * 100

np.float64(8.1)

In [ ]:
# fill discount_pict
telco['Discount_Pct'].fillna(0, inplace=True)

/tmp/ipykernel_3265/3524057578.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  telco['Discount_Pct'].fillna(0, inplace=True)

In [ ]:
telco.isnull().sum()

Txn_ID                0
Subscriber_ID       568
Activation_Date       0
City                  0
Province              0
Package_Type          0
Package_Name          0
Usage_GB              0
Package_Price         0
Discount_Pct          0
Recharge_Amount       0
Network_Cost          0
Channel               0
Payment_Method        0
Tenure_Days           0
Churn_Flag         3327
NPS_Score             0
Target_ARPU           0
dtype: int64

In [ ]:
# handle missing Subscriber_ID fill dengan unknown
telco['Subscriber_ID'].fillna('Unknown', inplace=True)

/tmp/ipykernel_3265/415346711.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  telco['Subscriber_ID'].fillna('Unknown', inplace=True)

### **Feature Engineering**

In [ ]:
# menambahkan kolom profit
telco['Profit'] = telco['Recharge_Amount'] - telco['Network_Cost']
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU,Profit
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,DIY,Data,Package_31,10,306.02,0.00,3060.20,2254.37,Retail,Cash,0,NaN,63,96010,805.83
1,TEL-000002,SUB1687,2024-07-10,Surabaya,Jawa Timur,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332,-17.38
2,TEL-000003,SUB3131,2024-03-13,Yogyakarta,DIY,Data,Package_61,14,194.08,0.10,1976.69,2069.26,Dealer,Transfer,81,N,96,154577,-92.57
3,TEL-000004,SUB4293,2025-02-11,Bandung,Jawa Barat,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707,1152.86
4,TEL-000005,SUB4930,2025-01-16,Surabaya,Jawa Timur,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593,566.24

In [ ]:
# menambahkan Kategori NPS_Score
# kategori < 51 buruk
# kategori >= 51 - 85 bagus
# kategori >= 85 bagus sekali

telco['NPS_Category'] = np.where(telco['NPS_Score'] < 51, 'Buruk',
np.where((telco['NPS_Score'] >= 51) & (telco['NPS_Score'] <= 85), 'Bagus', 'Bagus Sekali'))
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU,Profit,NPS_Category
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,DIY,Data,Package_31,10,306.02,0.00,3060.20,2254.37,Retail,Cash,0,NaN,63,96010,805.83,Bagus
1,TEL-000002,SUB1687,2024-07-10,Surabaya,Jawa Timur,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332,-17.38,Bagus Sekali
2,TEL-000003,SUB3131,2024-03-13,Yogyakarta,DIY,Data,Package_61,14,194.08,0.10,1976.69,2069.26,Dealer,Transfer,81,N,96,154577,-92.57,Bagus Sekali
3,TEL-000004,SUB4293,2025-02-11,Bandung,Jawa Barat,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707,1152.86,Bagus
4,TEL-000005,SUB4930,2025-01-16,Surabaya,Jawa Timur,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593,566.24,Buruk

In [ ]:
# ARPU_Gap --> selisih pendapatan aktual (Recharge_Amount) vs target (Target_ARPU)
telco['ARPU_Gap'] = telco['Recharge_Amount'] - telco['Target_ARPU']

# kategorikan cat_target_ARPU jika positif = mencapai (Y) dan negatif = tidak mencapai (N)
def cat_target_ARPU (x) :
  if x <= 0 :
    return 'N'
  else :
    return 'Y'
telco['cat_target_ARPU'] = telco['ARPU_Gap'].apply(cat_target_ARPU)
telco.head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,...,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU,Profit,NPS_Category,ARPU_Gap,cat_target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,DIY,Data,Package_31,10,306.02,0.00,...,Retail,Cash,0,NaN,63,96010,805.83,Bagus,-92949.80,N
1,TEL-000002,SUB1687,2024-07-10,Surabaya,Jawa Timur,Data,Package_12,17,133.81,0.95,...,Dealer,Ewallet,57,NaN,86,76332,-17.38,Bagus Sekali,-76218.26,N
2,TEL-000003,SUB3131,2024-03-13,Yogyakarta,DIY,Data,Package_61,14,194.08,0.10,...,Dealer,Transfer,81,N,96,154577,-92.57,Bagus Sekali,-152600.31,N
3,TEL-000004,SUB4293,2025-02-11,Bandung,Jawa Barat,Voice,Package_94,7,794.58,0.15,...,Online,Ewallet,108,NaN,54,91707,1152.86,Bagus,-86979.25,N
4,TEL-000005,SUB4930,2025-01-16,Surabaya,Jawa Timur,Data,Package_34,13,81.33,0.05,...,Online,Transfer,19,Y,27,182593,566.24,Buruk,-181004.89,N

In [ ]:
# Menampilkan baris di mana cat_target_ARPU bernilai 'Y'
telco[telco['cat_target_ARPU'] == 'Y'].head()

,Txn_ID,Subscriber_ID,Activation_Date,City,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,...,Channel,Payment_Method,Tenure_Days,Churn_Flag,NPS_Score,Target_ARPU,Profit,NPS_Category,ARPU_Gap,cat_target_ARPU
90,TEL-000091,Unknown,2024-01-06,Jakarta,DKI,Combo,Package_53,4631,493.89,0.20,...,Dealer,Transfer,67,N,56,191242,-122801.66,Bagus,1638521.67,Y
178,TEL-000179,SUB2405,2025-02-26,Yogyakarta,DIY,Data,Package_89,3265,293.30,0.00,...,Dealer,Ewallet,0,Y,1,153490,46670.52,Buruk,804134.50,Y
218,TEL-000219,SUB3101,2024-04-20,Surabaya,Jawa Timur,Voice,Package_91,3226,77.07,0.15,...,Retail,Cash,66,NaN,-14,176594,11974.30,Buruk,34739.65,Y
228,TEL-000229,SUB3064,2025-09-22,Yogyakarta,DIY,Combo,Package_96,11,123918.27,0.10,...,Dealer,Transfer,75,N,50,184362,-230976.70,Buruk,1042428.87,Y
234,TEL-000235,SUB4342,2023-10-13,Jakarta,DKI,Data,Package_15,6,94317.51,0.15,...,Dealer,Ewallet,90,Y,26,161466,-67938.85,Buruk,319553.30,Y

### **Handle Missing Value Churn_Flag**
Dikerjakan di SQL

# SAVE TO SQL